In [1]:
! python -c 'tensorflow' || pip tensorflow --user

In [5]:
import tensorflow as tf
import os
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [6]:
print(tf.__version__)

2.10.1


In [11]:
# Load Data and review contents
iris_data = pd.read_csv("iris.csv")
print("-----------------\nLoaded Data : \n-----------------")

-----------------
Loaded Data : 
-----------------


In [12]:
print(iris_data.head())

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa


In [14]:
# Using a label encoder to convert String to numeric values for the target variables
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()
iris_data['Species'] = label_encoder.fit_transform(iris_data['Species'])

In [15]:
# Converting an input to a numpy array
np_iris = iris_data.to_numpy()

In [16]:
# Seperating feature and target variables
X_data = np_iris[:, 0:4]
Y_data = np_iris[:,-1]

In [19]:
# Validating feature variables
print("\nFeature variables before scaling : \n-----------------")
print(X_data[:5, :])
# Validating target variables
print("\nTarget variables before scaling : \n-----------------")
print(Y_data[:5])


Feature variables before scaling : 
-----------------
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]

Target variables before scaling : 
-----------------
[0. 0. 0. 0. 0.]


In [20]:
# Creating a scalar model to fit the input data
scaler = StandardScaler().fit(X_data)

# Scaling the neumeric feature variables
X_data = scaler.transform(X_data)

In [21]:
#Converting target variable as a one-hot-encoding array to create 3 columns to represent species  
Y_data = tf.keras.utils.to_categorical(Y_data, 3)

In [22]:
# Validating feature variables
print("\nFeature variables after scaling : \n-----------------")
print(X_data[:5, :])

# Validating target variables
print("\nTarget variables after scaling : \n-----------------")
print(Y_data[:5])


Feature variables after scaling : 
-----------------
[[-0.90068117  1.01900435 -1.34022653 -1.3154443 ]
 [-1.14301691 -0.13197948 -1.34022653 -1.3154443 ]
 [-1.38535265  0.32841405 -1.39706395 -1.3154443 ]
 [-1.50652052  0.09821729 -1.2833891  -1.3154443 ]
 [-1.02184904  1.24920112 -1.34022653 -1.3154443 ]]

Target variables after scaling : 
-----------------
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]


In [24]:
# Splitting training and test data
X_train, X_test, Y_train, Y_test = train_test_split(X_data, Y_data, test_size=0.10)

print("\nTrain Test Dimentions : \n-----------------")
print(X_train.shape, Y_train.shape, X_test,shape, Y_test.shape)


Train Test Dimentions : 
-----------------
(135, 4)
